coordinates:
  not_ready_coords: [2009, 177]
  ready_voice_coords: [2002, 208]
  call_button_coords: [1997, 934]
  voicemail_noanswer_coords: [2349, 760]
  end_call_coords: [2066, 876]
  set_disposition_coords: [2064, 935]
  call_back_coords: [1940, 375]
  end_interaction_coords: [2067, 934]
  confirm_coords: [2057, 767]
  cancel_coords_0: [2049, 619]
  cancel_coords_1: [2055, 618]
  cancel_coords_2: [2056, 652]
  cancel_coords_3: [2066, 612]
  save_end_call_coords: [2351, 198]
  dropdown_coords: [2439, 724]
  voicemail_option_coords: [2429, 774]
